name: API CI Wokrflow
# on: [push] # Para un solo proyecto
on:
  # Esto es porque es una aplicación 'monorepo'
  push:
    paths:
      - './api/**'
      - '.github/workflows/api-ci.yml'
defaults:
  run:
    working-directory: './api'

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run Static Tests (ESLint)
        shell: bash
        run: npm run lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install dependencies
        shell: bash
        run: npm ci
      - name: Run Unit Tests
        shell: bash
        run: npm run test


